# Generated by Django 5.0 on 2023-12-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
